# Generated by Django 3.2.9 on 2021-12-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_userdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
