# Generated by Django 3.2.9 on 2021-12-04 01:22

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_alter_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
